# wallet-transfer 配置文件示例

# 网络配置
networks:
  ethereum:
    name: "Ethereum Mainnet"
    chain_id: 1
    rpc_url: "https://mainnet.infura.io/v3/YOUR_INFURA_KEY"
    symbol: "ETH"
    decimals: 18
  
  goerli:
    name: "Ethereum Goerli Testnet"
    chain_id: 5
    rpc_url: "https://goerli.infura.io/v3/YOUR_INFURA_KEY"
    symbol: "ETH"
    decimals: 18
  
  sepolia:
    name: "Ethereum Sepolia Testnet"
    chain_id: 11155111
    rpc_url: "https://sepolia.infura.io/v3/YOUR_INFURA_KEY"
    symbol: "ETH"
    decimals: 18
  
  bsc:
    name: "BSC Mainnet"
    chain_id: 56
    rpc_url: "https://bsc-dataseed.binance.org/"
    symbol: "BNB"
    decimals: 18
  
  bsc-testnet:
    name: "BSC Chapel Testnet"
    chain_id: 97
    rpc_url: "https://data-seed-prebsc-1-s1.binance.org:8545/"
    symbol: "BNB"
    decimals: 18
  
  polygon:
    name: "Polygon Mainnet"
    chain_id: 137
    rpc_url: "https://polygon-rpc.com/"
    symbol: "MATIC"
    decimals: 18
  
  mumbai:
    name: "Polygon Mumbai Testnet"
    chain_id: 80001
    rpc_url: "https://rpc-mumbai.maticvigil.com/"
    symbol: "MATIC"
    decimals: 18

# 默认设置
defaults:
  network: "sepolia"
  private_keys_source: "env"  # env, file, interactive
  concurrent: false
  workers: 10
  confirmations: 1
  timeout: 300
  output: "table"  # table, json, csv

# 转账配置示例
transfer_examples:
  # 一对一转账示例
  one_to_one:
    mode: "one_to_one"
    recipients:
      - "0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6"
      - "0x8ba1f109551bD432803012645Hac136c5c8b4d8b6"
    amount:
      fixed: "1000000000000000000"  # 1 ETH in wei
      unit: "ether"
    gas:
      auto: true
      gas_limit: 21000
    concurrent: false
    confirmations: 1
    timeout: 300

  # 一对多转账示例
  one_to_many:
    mode: "one_to_many"
    recipients:
      - "0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6"
      - "0x8ba1f109551bD432803012645Hac136c5c8b4d8b6"
      - "0x9ca2f109551bD432803012645Hac136c5c8b4d8b6"
    amount:
      min_range: "100000000000000000"   # 0.1 ETH
      max_range: "1000000000000000000"  # 1 ETH
      unit: "ether"
    gas:
      auto: true
    concurrent: true
    workers: 5
    confirmations: 1
    timeout: 300

  # 多对一转账示例
  many_to_one:
    mode: "many_to_one"
    recipients:
      - "0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6"
    amount:
      fixed: "500000000000000000"  # 0.5 ETH
      unit: "ether"
    gas:
      auto: true
    concurrent: true
    workers: 10
    confirmations: 1
    timeout: 300

  # 多对多转账示例
  many_to_many:
    mode: "many_to_many"
    recipients:
      - "0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6"
      - "0x8ba1f109551bD432803012645Hac136c5c8b4d8b6"
    amount:
      min_range: "10000000000000000"    # 0.01 ETH
      max_range: "100000000000000000"   # 0.1 ETH
      unit: "ether"
    gas:
      auto: true
    concurrent: true
    workers: 20
    confirmations: 1
    timeout: 300

# 加密钱包配置示例（需要密码解密）
# wallets:
#   - name: "wallet1"
#     encrypted_private_key: "encrypted_data_here"
#     salt: "random_salt_here"
#   - name: "wallet2"
#     encrypted_private_key: "encrypted_data_here"
#     salt: "random_salt_here"